import 'package:flutter/material.dart';

const kprimaryBackGroundColor = Color(0xffffffff);
const String kScrean1 = '/page1';
const String kScrean2 = '/page2';
const String kScrean3 = '/page3';
const String kLoginScrean = '/login_screan';
const String kSignUpScrean = '/Sign_up_screan';
const String kSignUpProcess = '/SignUp_process';
const String kPaymentMethod = '/payment_method';
const String kUplaodScrean = '/Upload_screan';
const String kUploadPreview = '/upload_preview';
const String kSetLocationScrean = '/set_location_screan';
const String kSignUpSuccessNotification = '/signUp_Notification_success';
const String kVertificationCodeScrean = '/Vertification_code_screan';
const String kForgetPasswordScrean = '/forget_password_screan';
const String kRestpasswordScrean = '/rest_password_screan';
const String kRestpasswordNoticationSuccess = '/restpassword_noticationsuccess';
const String kHomeScrean = 'home_screan';
const String kResutrantScrean = 'resturant_home_screan';
const String kSearchPageScrean = 'search_page_screan';
const String kAllRestaurantScrean = 'all_restaurant_page';
const String kMealDetailScrean = 'meal_detail_screan';
